export const PHONEMES = [
  { id: 'ae', symbol: '/æ/', name: 'A abierta', description: 'Entre "a" y "e", boca bien abierta',
    words: [
      { word: 'cat', ipa: '/kæt/', meaning: 'gato' },
      { word: 'bat', ipa: '/bæt/', meaning: 'murciélago' },
      { word: 'hat', ipa: '/hæt/', meaning: 'sombrero' },
      { word: 'apple', ipa: '/ˈæpəl/', meaning: 'manzana' },
      { word: 'man', ipa: '/mæn/', meaning: 'hombre' },
      { word: 'hand', ipa: '/hænd/', meaning: 'mano' },
      { word: 'thank', ipa: '/θæŋk/', meaning: 'agradecer' },
      { word: 'flag', ipa: '/flæɡ/', meaning: 'bandera' },
    ]},
  { id: 'ih', symbol: '/ɪ/', name: 'I corta', description: '"i" corta y relajada, boca más abierta',
    words: [
      { word: 'ship', ipa: '/ʃɪp/', meaning: 'barco' },
      { word: 'sit', ipa: '/sɪt/', meaning: 'sentarse' },
      { word: 'fish', ipa: '/fɪʃ/', meaning: 'pez' },
      { word: 'kid', ipa: '/kɪd/', meaning: 'niño' },
      { word: 'six', ipa: '/sɪks/', meaning: 'seis' },
      { word: 'list', ipa: '/lɪst/', meaning: 'lista' },
      { word: 'pick', ipa: '/pɪk/', meaning: 'elegir' },
      { word: 'busy', ipa: '/ˈbɪzi/', meaning: 'ocupado' },
    ]},
  { id: 'iy', symbol: '/iː/', name: 'I larga', description: '"i" larga y tensa',
    words: [
      { word: 'sheep', ipa: '/ʃiːp/', meaning: 'oveja' },
      { word: 'seat', ipa: '/siːt/', meaning: 'asiento' },
      { word: 'tree', ipa: '/triː/', meaning: 'árbol' },
      { word: 'green', ipa: '/ɡriːn/', meaning: 'verde' },
      { word: 'cheese', ipa: '/tʃiːz/', meaning: 'queso' },
      { word: 'meet', ipa: '/miːt/', meaning: 'conocer' },
      { word: 'feet', ipa: '/fiːt/', meaning: 'pies' },
      { word: 'easy', ipa: '/ˈiːzi/', meaning: 'fácil' },
    ]},
  { id: 'uh', symbol: '/ʊ/', name: 'U corta', description: '"u" corta y relajada',
    words: [
      { word: 'book', ipa: '/bʊk/', meaning: 'libro' },
      { word: 'look', ipa: '/lʊk/', meaning: 'mirar' },
      { word: 'foot', ipa: '/fʊt/', meaning: 'pie' },
      { word: 'good', ipa: '/ɡʊd/', meaning: 'bueno' },
      { word: 'put', ipa: '/pʊt/', meaning: 'poner' },
      { word: 'wood', ipa: '/wʊd/', meaning: 'madera' },
      { word: 'cook', ipa: '/kʊk/', meaning: 'cocinar' },
      { word: 'pull', ipa: '/pʊl/', meaning: 'tirar' },
    ]},
  { id: 'uw', symbol: '/uː/', name: 'U larga', description: '"u" larga y tensa',
    words: [
      { word: 'boot', ipa: '/buːt/', meaning: 'bota' },
      { word: 'food', ipa: '/fuːd/', meaning: 'comida' },
      { word: 'moon', ipa: '/muːn/', meaning: 'luna' },
      { word: 'spoon', ipa: '/spuːn/', meaning: 'cuchara' },
      { word: 'blue', ipa: '/bluː/', meaning: 'azul' },
      { word: 'shoe', ipa: '/ʃuː/', meaning: 'zapato' },
      { word: 'school', ipa: '/skuːl/', meaning: 'escuela' },
      { word: 'true', ipa: '/truː/', meaning: 'verdadero' },
    ]},
  { id: 'ah', symbol: '/ʌ/', name: 'A apagada', description: 'Vocal central, "a" muy corta y apagada',
    words: [
      { word: 'cup', ipa: '/kʌp/', meaning: 'taza' },
      { word: 'love', ipa: '/lʌv/', meaning: 'amor' },
      { word: 'sun', ipa: '/sʌn/', meaning: 'sol' },
      { word: 'fun', ipa: '/fʌn/', meaning: 'diversión' },
      { word: 'bus', ipa: '/bʌs/', meaning: 'autobús' },
      { word: 'mother', ipa: '/ˈmʌðər/', meaning: 'madre' },
      { word: 'much', ipa: '/mʌtʃ/', meaning: 'mucho' },
      { word: 'lunch', ipa: '/lʌntʃ/', meaning: 'almuerzo' },
    ]},
  { id: 'er', symbol: '/ɜː/', name: 'Vocal central larga', description: 'Vocal larga, lengua en posición central',
    words: [
      { word: 'bird', ipa: '/bɜːd/', meaning: 'pájaro' },
      { word: 'word', ipa: '/wɜːd/', meaning: 'palabra' },
      { word: 'girl', ipa: '/ɡɜːl/', meaning: 'chica' },
      { word: 'work', ipa: '/wɜːk/', meaning: 'trabajo' },
      { word: 'first', ipa: '/fɜːst/', meaning: 'primero' },
      { word: 'learn', ipa: '/lɜːn/', meaning: 'aprender' },
      { word: 'turn', ipa: '/tɜːn/', meaning: 'girar' },
      { word: 'nurse', ipa: '/nɜːs/', meaning: 'enfermera' },
    ]},
  { id: 'schwa', symbol: '/ə/', name: 'Schwa', description: 'Vocal débil en sílabas átonas',
    words: [
      { word: 'about', ipa: '/əˈbaʊt/', meaning: 'sobre, acerca' },
      { word: 'banana', ipa: '/bəˈnɑːnə/', meaning: 'plátano' },
      { word: 'sofa', ipa: '/ˈsəʊfə/', meaning: 'sofá' },
      { word: 'lemon', ipa: '/ˈlemən/', meaning: 'limón' },
      { word: 'common', ipa: '/ˈkɒmən/', meaning: 'común' },
      { word: 'problem', ipa: '/ˈprɒbləm/', meaning: 'problema' },
      { word: 'system', ipa: '/ˈsɪstəm/', meaning: 'sistema' },
      { word: 'again', ipa: '/əˈɡen/', meaning: 'otra vez' },
    ]},
  { id: 'v', symbol: '/v/', name: 'V labiodental', description: 'Dientes superiores tocando el labio inferior',
    words: [
      { word: 'very', ipa: '/ˈveri/', meaning: 'muy' },
      { word: 'voice', ipa: '/vɔɪs/', meaning: 'voz' },
      { word: 'vote', ipa: '/vəʊt/', meaning: 'voto' },
      { word: 'visit', ipa: '/ˈvɪzɪt/', meaning: 'visitar' },
      { word: 'live', ipa: '/lɪv/', meaning: 'vivir' },
      { word: 'never', ipa: '/ˈnevər/', meaning: 'nunca' },
      { word: 'travel', ipa: '/ˈtrævəl/', meaning: 'viajar' },
      { word: 'seven', ipa: '/ˈsevən/', meaning: 'siete' },
    ]},
  { id: 'z', symbol: '/z/', name: 'S sonora', description: 'Como una "s" pero con vibración de cuerdas',
    words: [
      { word: 'zoo', ipa: '/zuː/', meaning: 'zoo' },
      { word: 'zero', ipa: '/ˈzɪərəʊ/', meaning: 'cero' },
      { word: 'easy', ipa: '/ˈiːzi/', meaning: 'fácil' },
      { word: 'busy', ipa: '/ˈbɪzi/', meaning: 'ocupado' },
      { word: 'music', ipa: '/ˈmjuːzɪk/', meaning: 'música' },
      { word: 'please', ipa: '/pliːz/', meaning: 'por favor' },
      { word: 'rose', ipa: '/rəʊz/', meaning: 'rosa' },
      { word: 'eyes', ipa: '/aɪz/', meaning: 'ojos' },
    ]},
  { id: 'sh', symbol: '/ʃ/', name: 'Sh', description: 'Como un "shhh" para pedir silencio',
    words: [
      { word: 'ship', ipa: '/ʃɪp/', meaning: 'barco' },
      { word: 'she', ipa: '/ʃiː/', meaning: 'ella' },
      { word: 'shoe', ipa: '/ʃuː/', meaning: 'zapato' },
      { word: 'fish', ipa: '/fɪʃ/', meaning: 'pez' },
      { word: 'wash', ipa: '/wɒʃ/', meaning: 'lavar' },
      { word: 'short', ipa: '/ʃɔːt/', meaning: 'corto' },
      { word: 'station', ipa: '/ˈsteɪʃən/', meaning: 'estación' },
      { word: 'special', ipa: '/ˈspeʃəl/', meaning: 'especial' },
    ]},
  { id: 'zh', symbol: '/ʒ/', name: 'Zh sonora', description: 'Versión sonora del "sh"',
    words: [
      { word: 'measure', ipa: '/ˈmeʒər/', meaning: 'medir' },
      { word: 'pleasure', ipa: '/ˈpleʒər/', meaning: 'placer' },
      { word: 'treasure', ipa: '/ˈtreʒər/', meaning: 'tesoro' },
      { word: 'vision', ipa: '/ˈvɪʒən/', meaning: 'visión' },
      { word: 'decision', ipa: '/dɪˈsɪʒən/', meaning: 'decisión' },
      { word: 'television', ipa: '/ˈtelɪvɪʒən/', meaning: 'televisión' },
      { word: 'usual', ipa: '/ˈjuːʒuəl/', meaning: 'usual' },
      { word: 'garage', ipa: '/ˈɡærɑːʒ/', meaning: 'garaje' },
    ]},
  { id: 'j', symbol: '/dʒ/', name: 'J inglesa', description: 'Empieza con "d" y termina en "zh"',
    words: [
      { word: 'judge', ipa: '/dʒʌdʒ/', meaning: 'juez' },
      { word: 'jump', ipa: '/dʒʌmp/', meaning: 'saltar' },
      { word: 'job', ipa: '/dʒɒb/', meaning: 'trabajo' },
      { word: 'joy', ipa: '/dʒɔɪ/', meaning: 'alegría' },
      { word: 'jacket', ipa: '/ˈdʒækɪt/', meaning: 'chaqueta' },
      { word: 'gym', ipa: '/dʒɪm/', meaning: 'gimnasio' },
      { word: 'orange', ipa: '/ˈɒrɪndʒ/', meaning: 'naranja' },
      { word: 'bridge', ipa: '/brɪdʒ/', meaning: 'puente' },
    ]},
  { id: 'h', symbol: '/h/', name: 'H aspirada', description: 'Aspiración suave, sin fricción de garganta',
    words: [
      { word: 'house', ipa: '/haʊs/', meaning: 'casa' },
      { word: 'hello', ipa: '/həˈləʊ/', meaning: 'hola' },
      { word: 'happy', ipa: '/ˈhæpi/', meaning: 'feliz' },
      { word: 'hand', ipa: '/hænd/', meaning: 'mano' },
      { word: 'head', ipa: '/hed/', meaning: 'cabeza' },
      { word: 'heart', ipa: '/hɑːt/', meaning: 'corazón' },
      { word: 'home', ipa: '/həʊm/', meaning: 'hogar' },
      { word: 'hope', ipa: '/həʊp/', meaning: 'esperanza' },
    ]},
  { id: 'ng', symbol: '/ŋ/', name: 'Ng final', description: '"ng" final, sin pronunciar la "g"',
    words: [
      { word: 'sing', ipa: '/sɪŋ/', meaning: 'cantar' },
      { word: 'song', ipa: '/sɒŋ/', meaning: 'canción' },
      { word: 'long', ipa: '/lɒŋ/', meaning: 'largo' },
      { word: 'king', ipa: '/kɪŋ/', meaning: 'rey' },
      { word: 'thing', ipa: '/θɪŋ/', meaning: 'cosa' },
      { word: 'young', ipa: '/jʌŋ/', meaning: 'joven' },
      { word: 'strong', ipa: '/strɒŋ/', meaning: 'fuerte' },
      { word: 'morning', ipa: '/ˈmɔːnɪŋ/', meaning: 'mañana' },
    ]},
  { id: 'w', symbol: '/w/', name: 'W consonántica', description: 'Labios bien redondeados al inicio',
    words: [
      { word: 'water', ipa: '/ˈwɔːtər/', meaning: 'agua' },
      { word: 'window', ipa: '/ˈwɪndəʊ/', meaning: 'ventana' },
      { word: 'what', ipa: '/wɒt/', meaning: 'qué' },
      { word: 'where', ipa: '/weər/', meaning: 'dónde' },
      { word: 'why', ipa: '/waɪ/', meaning: 'por qué' },
      { word: 'work', ipa: '/wɜːk/', meaning: 'trabajo' },
      { word: 'world', ipa: '/wɜːld/', meaning: 'mundo' },
      { word: 'one', ipa: '/wʌn/', meaning: 'uno' },
    ]},
];

export const PHONEME_SOUND = {
  ae:    'aaa',
  ih:    'ih',
  iy:    'eee',
  uh:    'oo',
  uw:    'oooo',
  ah:    'uh',
  er:    'urrr',
  schwa: 'uh',
  v:     'vvv',
  z:     'zzz',
  sh:    'shhh',
  zh:    'zhuh',
  j:     'juh',
  h:     'huh',
  ng:    'nnng',
  w:     'wah',
};
